import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./utils/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}>

        {/* Navbar */}
        <Navbar />

        {/* Background Image Fixed + Overlay */}
        <div className="fixed inset-0 -z-50">
          <div
            className="absolute inset-0 bg-cover bg-center"
            style={{ backgroundImage: "url('/assets/bg.webp')" }}
          ></div>
          <div className="absolute inset-0 bg-linear-to-br from-blue-950 to-blue-900 opacity-60"></div>
        </div>

        {/* Page Content */}
        <div className="relative z-10">
          {children}
        </div>

      </body>
    </html>
  );
}
